### ISSUE TITLE
Can't run Arma with ALiVE Mod

### ISSUE THREAD

**Issue by EliteMaster512** [ALiVEOS/ALiVE.OS#297]
I've been playing Arma for months now. Every other mod I've installed works, but the ALiVE mod does not.

With only the ALiVE Mod (and CBA3) installed, I get an error as soon as the game renders anything.

![](https://i.gyazo.com/9f14e71c6f4c37be6632420608260bb9.png)

I have 16 gb of DDR3 RAM, and well over that amount on the harddrive. What could be the issue?

This message pops up afterwards:

![](https://i.gyazo.com/da0dd7e3b0e78f0730317c9addf2b9b0.png)

**Comment by HeroesandvillainsOS** [comment]
Try rolling back to an older version of CBA and see if the problems continue. CBA just updated and introduced an issue where ALiVE can't initialize properly and therefore won't work.

**Comment by EliteMaster512** [comment]
Should CBA 3.1.2 work? Cause that's the version I'm using.

**Comment by highhead** [comment]
just roll back to CBA version before that. It will produce another bug that we have fixed in ALiVE but it will be at least be working---

**Comment by EliteMaster512** [comment]
Error still occurs with CBA_A3, versions 3.1.2, 3.1.1, 3.1.0, and 3.0.0.

Is there something potentially wrong with my ssd? With my installation of the mod? With my pc itself?

**Comment by HeroesandvillainsOS** [comment]
I don't think these errors are going to be specifically related to ALiVE. Can you try running just ALiVE and CBA (the older version) and nothing else and see if it loads? The only time I've had those errors myself is when using suspect mods. Let's try to remove as many variables as possible to narrow doe the cause. 

And please, use Arma 3 stable 1.66. No old versions of Arma, and no RC or dev branch.

**Comment by EliteMaster512** [comment]
I'm using only 1.66 Arma 3, ALiVE, and CBA_A3.

I've tried versions 3.1.2, 3.1.1, 3.1.0, and 3.0.0, all of which do not work unfortunately.

I'm re-installing Arma 3 on my second hard drive to see if that fixes it. Thanks for your help and patience so far though 👍

**Comment by EliteMaster512** [comment]
Here's the error dump: https://www.dropbox.com/sh/kvalx8ffcb0eg4y/AADWcUd76S8seLwICVPOB2GRa?dl=0

**Comment by EliteMaster512** [comment]
Can anyone provide support?

**Comment by coachwn** [comment]
I haven't seen it happen with just ALiVE and CBA as the only mods. I have seen that type of error associated with a bad sector on a drive or a bad RAM stick. I am guessing that you have done troubleshooting on the RAM and run tests on your SSD? I do believe that most of the issues we are seeing with Arma could be associated with SSD's for some reason. I don't have proof or any way to prove it otherwise but there are just too many people with SSD's as their game drive that are having issues with Arma doing stuff. I will take a look at your error stuff and see why my old brain can conjur up for you to check.

**Comment by EliteMaster512** [comment]
Thanks so much coachwn.

A while back I tested my RAM sticks and they came out fine. They're Crucial Ballistix, and I've heard they're a good brand.

I could test the SSD, but I haven't had issues with it at any other point than this.

**Comment by EliteMaster512** [comment]
Update: Used SSD Life and it says the drive is healthy... I'm downloading another program to check its status now though.

**Comment by coachwn** [comment]
You mentioned you were installing on a 2nd drive; have you had a chance to check that? Have you done an integrity check via Steam on the previous installation of Arma? Just looking at DXDIAG that would be where I would start after running a check on the drive. 

One last question before I go offline? What map are you attempting to load for the mission that causes this to happen? There might be something in the BI minidump files that you will have to go to the BI Feedback Tracker to search for there.

**Comment by EliteMaster512** [comment]
Alright so to answer your questions:

I've not checked the HDD but I will now.

I've constantly been verifying the gamefiles' integrity via steam; all files are valid.

I've tried loading Stratis, Altis, and number of other modded maps like Chernarus.

...but it seems that it crashes regardless of map, considering that the game crashes just loading the start menu, if the background world is rendered.

I've just now deleted everything on my C: drive relating to Arma 3, and will reinstall everryyyything.

**Comment by EliteMaster512** [comment]
Also I've just tried loading in the editor, no mission even.

**Comment by coachwn** [comment]
OK I was asking about the terrain because we were just running a mission on Chernarus and it never failed to cause issues that created either extreme server lag to the point of the server coming to a full stop or it crashed the clients to the desktop. Either one was enough to cripple and nearly kill the momentum that we had with our communities milsim side. Still not sure if it was ALiVE related with the shear number of objectives we had loading in or the number of profiles that the AI was attempting to load in as well. Either way there were times we were unable to load the mission with a server that was more than capable of handling more complex missions and terrains.

**Comment by coachwn** [comment]
I will look into this further in the morning. Got an early day at work tomorrow.

**Comment by EliteMaster512** [comment]
Thanks so much. Arma 3 just reinstalled and I'll try again from the very ground up. New user and all.

**Comment by EliteMaster512** [comment]
Alright... so update: Reinstalling everything from the very ground up has things working again... I think. Now  the first time I tried loading into a map there was an error, but I think that was a startup thing because Apex hadn't even properly loaded until I started the game again.

Now I can get into the editor, and will see how much I can do as of now.

**Comment by EliteMaster512** [comment]
Update: As of now things are running okay with a complete reinstall.

Why uninstalling the game from Steam and just reinstalling ALiVE didn't fix it, but the issue seems to be getting better...

...reinstalling mod repository now and will see if this issue happens again. Thank you all for your patience and I'll let you know what happens asap.

**Comment by SpyderBlack723** [comment]
Essentially, this is something completely out of our hands. I would do as coachwn suggested and submit the dump logs to BI in hopes they can spot any issues.

Glad it's at least working now.
