### ISSUE TITLE
Transport chopper unresponsive after failed slingload 

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#63]
Just wanted to report a quick bug. So far I've only tested a manually placed chopper with this setVariable ["CS_TYPE","TRANSPORT"]; in its init synced to CS.

When you use the tablet, select slingloading, select an object in the new drop down, and click on an area in the map; in the event the chopper does not successfully slingload an object (which is very often), the transport chopper becomes unresponsive. It can only be forced to RTB but no additional commands can be given.

At least not within 5-10 minutes of the unsuccessful attempt.

I've seen this happen with the vanilla Huron and vanilla (camo) Ghosthawk.

**Comment by tupolov** [comment]
Ok, so clarification on use...

1. Click on map first to specify the area where the object is.
2. Then choose object.

I will update code to eliminate listing any objects the specific chopper cannot pickup.

**Comment by HeroesandvillainsOS** [comment]
Ah. My whole American thing of needing to read and do stuff from left to right fails me again!

Yeah, the system can use some fine tuning, honestly. It's very very easy to attempt an unsuccessful slingloading. It's an amazing feature though.

I'll try it the other way around and report back.

**Comment by tupolov** [comment]
Ok, so testing again. Order is a bit funky and needs to be improved.

Select Unit.
Click on Map area of object
Select Slingloading
Select Object

**Comment by HeroesandvillainsOS** [comment]
Thanks Tupolov. For future consideration, long-term, does the list that generates on the drop down have (or could possibly have) any insight on the location of the object without the need for the map click? The list seems to generate from know objects within the world. Possible for it to also know the object's location?

For down the road in a perfect world filled with unicorns and where scripting is easy:

1. Click on unit 
2. Click on slingloading
3. Click on object from the drop down (because it "knows" where the item is)
4. Click confirm

Item gets slingloaded. Again, this is just a "wish" as I wouldn't expect this to be an easy thing to accomplish.

**Comment by tupolov** [comment]
In Arma you never want a list of every slingloadable object on the map, could be hundreds... and its a performance nightmare.

I've fixed it so that:

1. Click on unit
2. Click on Slingloading (list of objects closest to player are listed)
3. Click on Map (list of objects closest to the map position are listed)
4. Choose object from list

Also you could
1. Click on unit
2. Click on map
3. Click on slingloading (list of objects closest to map position are listed)
4. Choose object from list

Also,
1. Choose object from list
2. Change your mind, click on map (list of objects get refreshed to those closest to new position)
etc..

**Comment by HeroesandvillainsOS** [comment]
Sounds good. I'm still having issues using 3CB (using a vanilla Huron though) trying to pick up droplist 3CB objects (such as their Coyote), but I'll know more after the next update when I can test with the refinements.

I like what you've added though. It sounds much better.
